replicaCount: 2

image:
  repository: "<ACR_LOGIN_SERVER>/patient-service"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

env: []   # add environment variables here if needed

secrets:
  k8sName: patient-secrets

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
